#!/usr/bin/env python3
"""
Export a study collection (default: "BYU-Hawaii Speeches") from the local
database as a standalone .sql file, for direct import into production via:

    mysql -u <user> -p jttbh < byuh_speeches.sql

Row ids (the auto-increment `id` columns) are deliberately omitted from the
generated INSERT statements — the insert-only schema only cares about
collectionID/sourceID (UUIDs, already globally unique), so production can
assign its own fresh ids with no collision risk against whatever ids already
exist there.

Only the current row per collectionID/sourceID is exported (the same
MAX(id)-per-key state every other part of the app reads) — not the full
insert-only edit history, since production has no prior version of this
collection to preserve history for.

Assumes the local admin user (userID/created_by) matches production's admin
user, which has held true since the last local/prod DB mirror sync. If your
local and prod admin userIDs have since diverged, edit the generated file's
userID/created_by values before importing.

Usage:
    python3 claude/export_byuh_speeches.py                        # writes byuh_speeches.sql
    python3 claude/export_byuh_speeches.py --out /tmp/byuh.sql
    python3 claude/export_byuh_speeches.py --collection-name "BYU Speeches"
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from app import create_app
from app.services.database import db_manager

import pymysql

COLLECTION_COLUMNS = ['collectionID', 'userID', 'name', 'description', 'mode', 'created', 'created_by']
SOURCE_COLUMNS = [
    'sourceID', 'collectionID', 'userID', 'category', 'title', 'subtitle',
    'author', 'url', 'audio_url', 'audio_length', 'order_by', 'scheduled_date',
    'created', 'created_by',
]


def get_collection(name):
    return db_manager.execute_one("""
        SELECT sc.collectionID, sc.userID, sc.name, sc.description, sc.mode,
               sc.created, sc.created_by
        FROM study_collection sc
        WHERE sc.name = %s
          AND sc.id = (SELECT MAX(sc2.id) FROM study_collection sc2 WHERE sc2.collectionID = sc.collectionID)
          AND sc.name IS NOT NULL
    """, (name,))


def get_sources(collection_id):
    return db_manager.execute_query("""
        SELECT ss.sourceID, ss.collectionID, ss.userID, ss.category, ss.title,
               ss.subtitle, ss.author, ss.url, ss.audio_url, ss.audio_length,
               ss.order_by, ss.scheduled_date, ss.created, ss.created_by
        FROM study_source ss
        WHERE ss.collectionID = %s
          AND ss.id = (SELECT MAX(ss2.id) FROM study_source ss2 WHERE ss2.sourceID = ss.sourceID)
          AND ss.title IS NOT NULL
        ORDER BY ss.order_by, ss.id
    """, (collection_id,))


def raw_connection():
    """Plain PyMySQL connection to the local DB, used only for its .escape()
    helper — all the actual reads go through db_manager as usual."""
    return pymysql.connect(
        host=os.environ.get('MYSQL_HOST', 'localhost'),
        port=int(os.environ.get('MYSQL_PORT', 3306)),
        user=os.environ.get('MYSQL_USER', 'jttbh'),
        password=os.environ.get('MYSQL_PASSWORD', 'jttbh'),
        database=os.environ.get('MYSQL_DB') or os.environ.get('MYSQL_DATABASE', 'jttbh'),
        charset='utf8mb4',
    )


def insert_statement(conn, table, columns, row):
    cols = ', '.join(f'`{c}`' for c in columns)
    vals = ', '.join(conn.escape(row[c]) for c in columns)
    return f'INSERT INTO `{table}` ({cols}) VALUES ({vals});'


def build_sql(conn, collection, sources):
    lines = [
        f'-- Export of study collection "{collection["name"]}" ({len(sources)} sources)',
        '-- Generated by claude/export_byuh_speeches.py',
        '-- ids are omitted so MySQL assigns fresh auto-increment values on import.',
        '',
        insert_statement(conn, 'study_collection', COLLECTION_COLUMNS, collection),
        '',
    ]
    lines += [insert_statement(conn, 'study_source', SOURCE_COLUMNS, s) for s in sources]
    return '\n'.join(lines) + '\n'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--collection-name', default='BYU-Hawaii Speeches',
                        help='Name of the study_collection to export (default: BYU-Hawaii Speeches)')
    parser.add_argument('--out', default='byuh_speeches.sql',
                        help='Output .sql file path (default: byuh_speeches.sql)')
    args = parser.parse_args()

    app = create_app()
    with app.app_context():
        collection = get_collection(args.collection_name)
        if not collection:
            print(f'ERROR: no collection named "{args.collection_name}" found.')
            sys.exit(1)
        sources = get_sources(collection['collectionID'])

        conn = raw_connection()
        try:
            sql = build_sql(conn, collection, sources)
        finally:
            conn.close()

    with open(args.out, 'w') as f:
        f.write(sql)

    print(f'Wrote 1 collection row + {len(sources)} source rows to {args.out}')


if __name__ == '__main__':
    main()
